### ISSUE TITLE
build mac app failed

### ISSUE THREAD

**Issue by sydonay** [ZeroX-DG/SnippetStore#64]
Some problems occurred while building the mac app

The error message:

Clearning compiled folder...
Done!
Compiling...
Compile success!
  • electron-builder version=20.19.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=7.3.3 appOutDir=dist/mac
[xmldom error]	invalid doc source
@#[line:0,col:undefined]
TypeError: Cannot read property 'documentElement' of undefined
    at parse (/Users/plancklong/OpenSource/SnippetStore/node_modules/plist/lib/parse.js:68:9)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/electron/electronMac.ts:51:25
From previous event:
    at createMacApp (/Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/out/electron/electronMac.js:245:17)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/electron/ElectronFramework.ts:48:11
    at Generator.next (<anonymous>)
From previous event:
    at beforeCopyExtraFiles (/Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/out/electron/ElectronFramework.js:167:17)
    at beforeCopyExtraFiles (/Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/electron/ElectronFramework.ts:123:14)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/platformPackager.ts:219:13
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at MacPackager.doPack (/Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/platformPackager.ts:158:165)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/macPackager.ts:80:95)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/packager.ts:369:24
    at Generator.next (<anonymous>)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:177:5)
From previous event:
    at Packager.doBuild (/Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/packager.ts:337:39)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/packager.ts:313:52
    at Generator.next (<anonymous>)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqCallback.oncomplete (fs.js:164:23)
From previous event:
    at Packager._build (/Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/packager.ts:290:133)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/packager.ts:286:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Packager.build (/Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/packager.ts:243:14)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/src/index.ts:52:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder/src/builder.ts:224:10)
    at /Users/plancklong/OpenSource/SnippetStore/node_modules/electron-builder/src/cli/cli.ts:46:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snippetstore@0.2.12 dist:mac: `npm run build && rimraf dist/ && electron-builder --mac`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snippetstore@0.2.12 dist:mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/plancklong/.npm/_logs/2020-10-18T14_54_21_441Z-debug.log

**Comment by ZeroX-DG** [comment]
I don't use mac so I can't really tell what's the problem here. But I'll try to find out what's wrong.

**Comment by sydonay** [comment]
> I don't use mac so I can't really tell what's the problem here. But I'll try to find out what's wrong.

Thank you for your help

**Comment by ash0080** [comment]
Same issue, but actually the .app has been built, you can find it in the /dist folder.
I've been using it for a few minutes now and haven't noticed any problems.

**Comment by sydonay** [comment]
> Same issue, but actually the .app has been built, you can find it in the /dist folder.
> I've been using it for a few minutes now and haven't noticed any problems.
> 
> But there should still be some mistakes.
> For example, the compiled app is still called Electron, without the specified icon.
> No help docs... Even though I don't know what is 'correct'.

You are right. the app in the /dist/mac folder. Thanks.

@ZeroX-DG But The problem of app still called Electron icon still exists
